CREATE DATABASE OBT_MODELLING;
USE OBT_MODELLING;
CREATE SCHEMA ARRAY_SCHEMA

DROP TABLE IF EXISTS orders;
CREATE TABLE IF NOT EXISTS orders (
    order_id INT,
    customer_id INT,
    product_ids ARRAY
);

INSERT INTO orders (order_id, customer_id, product_ids) 
SELECT 1, 1,  ARRAY_CONSTRUCT(101, 102, 103)
UNION ALL
SELECT 2, 1,  ARRAY_CONSTRUCT(104, 105)
UNION ALL
SELECT 3, 2, ARRAY_CONSTRUCT(106, 107, 108)
UNION ALL
SELECT 4, 2, ARRAY_CONSTRUCT(109, 110)

